repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.3.0
    hooks:
      - id: eslint
        files: \.(js|ts)$
        types: [file]
        additional_dependencies:
          - eslint@9.26.0
          - '@typescript-eslint/eslint-plugin@8.32.1'
          - '@typescript-eslint/parser@8.32.1'
          - eslint-config-prettier@10.1.5
          - eslint-plugin-prettier@5.4.0
          - prettier@3.5.3
          - typescript@5.8.3 